name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install six
        run: pip install six
      
      - name: Install Nativescript
        run: |
          npm install -g nativescript
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build --if-present

      - name: Run unit tests
        run: npm run test:unit

      